version: 2
jobs:
  build:
  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm i --no-audit -g eslint && eslint .
workflows:
  version: 2
  test:
    jobs:
      - test