version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: sudo npm i --no-audit -g eslint
      - run:
          command: |
            mkdir -p ~/reports
            eslint . --format junit --output-file ~/reports/eslint.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
